baseurl = "https://www.groovestomp.com"
title = "GrooveStomp"
hqlanguageCode = "en-us"

[params]
author = "Aaron Oman"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[pagination]
Paginate = 10
PaginatePath = "page"